on:
  schedule:
    - cron: "0 0 1,15 * *"
    
jobs:
  scrape:
    runs-on: ubuntu-latest
    
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          packages: |
            any::RSelenium
            any::countrycode
            any::tidyverse
            any::rvest
            any::janitor
            any::zoo
            any::WDI
            any::rjson
            any::httr
            any::readxl
            any::RCurl
            any::pxR
            any::netstat
            any::curl
            
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
          
    
      - name: Rscript run
        run: |
          Rscript oecs_scorecard_pull.R
          
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m 'Update data' || echo "Update data"
          git push origin --force || echo "Update data"
